### ISSUE TITLE
Use Gadfly for plotting

### ISSUE THREAD

**Issue by YingboMa** [mauro3/IVPTestSuite.jl#14]
Gadfly has better interactive, and it can even save the plot using a .js.svg and .svg format.

https://github.com/YingboMa/plot-comparison/blob/master/PyPlot.js.svg

https://github.com/YingboMa/plot-comparison/blob/master/Gadfly.js.svg

PS: Download the files and open them in an appropriate browser.

**Comment by obiajulu** [comment]
I like this idea and think this might be the right direction to go. I think there are some big design questions which still need to be worked out. Overall, I think everyone agrees that IVPTestSuite would be best if it could be run from the terminal and generate a html like output. I think Gadfly would be nice for this, the only question is how well is the package maintained.

**Comment by ChrisRackauckas** [comment]
A much better idea would be to use Plots.jl recipes. Then you could use Gadfly if you wanted, or PyPlot, etc.

**Comment by mauro3** [comment]
The reason I thought to go with PyPlot was its stability vs Plots.jl.  Considering this package doesn't get a lot of love, I thought best to use something stable.  I don't use Gadfly myself, so I didn't consider it.  I think zooming is not that relevant for the plots produced, so that is not really an issue.

**Comment by ChrisRackauckas** [comment]
I see. That sounds reasonable, though I think the recipe interface is pretty stable now.
